



```{r initialize, echo=FALSE,results='hide',message=FALSE,warning=FALSE}
# Initialize!

# Stop R from interpreting strings as factors. 
# When you want factors, you'll know it.
options(stringsAsFactors = FALSE)

# Load up the requisite packages
library(knitr)     # It's a knitr document, after all...
library(to1check)  # All TO1-related functions
library(plyr)      # For the count() and arrange() functions
library(lubridate) # For calculating years of follow-up
library(binom)     # For Bayesian binomial credible intervals
library(ggplot2)
library(mpmisc)    # For printing data.frames nicely



# Set default chunk options
opts_chunk$set(echo = FALSE,
               results = 'asis',
               message = FALSE,
               warning = FALSE,
               error = TRUE,
               fig.width = 10)



# Set up some colors to use throughout
colorwheel <- c( "#F03B20", "#31A354", "#1F78B4")

# Load the ggplot2 theme
source(file.path("..", "css", "theme_tbesc.r"))


# Load the local info (edit this if your results are wrong)
local_facts <- read.csv(file.path("..", "local_facts.csv"))

# Load the latest cleaned data
load(local_facts$datapath)

# Identify those who were successfully enrolled - we'll generally disregard 
# those who declined or who didn't complete enrollment 

enrolled <- with(to1clean$master,
    StudyID[!CloseReason %in% c("Didn't complete enrollment", 
                                "Withdrew", 
                                "Not eligible")]
)


# Set up subsets of only enrolled, eligible participants
enrolled_master <- to1clean$master[to1clean$master$StudyID %in% enrolled, ]

enrolled_preenroll <- to1clean$preenrollment[to1clean$preenrollment$StudyID 
                                             %in% enrolled, ]

enrolled_medhist <- to1clean$medicalhistory[to1clean$medicalhistory$StudyID
                                            %in% enrolled, ]

# Set a universal order for the result class variable
result_class_order <- c("Triple Positive", 
                        "TST+, QFT+, Borderline TSPOT",
                        "Dual Pos, TST and QFT",
                        "Dual Pos, TST and TSPOT",
                        "TST+, QFT-, Borderline TSPOT",
                        "Dual Pos, QFT and TSPOT", 
                        "TST-, QFT+, Borderline TSPOT",
                        "Isolated QFT+", 
                        "Isolated TSPOT+", 
                        "Isolated TST+",
                        "TST-, QFT-, Borderline TSPOT",
                        "Triple Negative", 
                        "Inconclusive")



# Cut ages into groups
to1clean$preenrollment$age.grp <- NA

to1clean$preenrollment$age.grp[to1clean$preenrollment$AgeAtEnrollment < 2] <- 
    "< 2"

to1clean$preenrollment$age.grp[to1clean$preenrollment$AgeAtEnrollment >= 2 &
                to1clean$preenrollment$AgeAtEnrollment <= 5] <- "2-5"

to1clean$preenrollment$age.grp[to1clean$preenrollment$AgeAtEnrollment >= 6 &
                to1clean$preenrollment$AgeAtEnrollment <= 12] <- "6-12"

to1clean$preenrollment$age.grp[to1clean$preenrollment$AgeAtEnrollment >= 13 &
                to1clean$preenrollment$AgeAtEnrollment <= 25] <- "13-25"

to1clean$preenrollment$age.grp[to1clean$preenrollment$AgeAtEnrollment >= 26 &
                to1clean$preenrollment$AgeAtEnrollment <= 39] <- "26-39"

to1clean$preenrollment$age.grp[to1clean$preenrollment$AgeAtEnrollment >= 40] <- "40+"

# Make it an ordered factor - keeps plots, tables, etc. in sensible order
to1clean$preenrollment$age.grp <- factor(to1clean$preenrollment$age.grp, 
                          levels = c("< 2", "2-5", "6-12", "13-25", 
                                     "26-39", "40+"),
                          ordered = TRUE
)






```

<h1 class='maintitle'>TBESC TO 1 Preliminary Analysis: `r local_facts$site`</h1>
<span class='maintitle'>Report generated at `r format(Sys.time())`</span>


```{r}

# Total enrolled so far (I need a better measure of this)
total_enrolled <- length(enrolled)

```



## Estimated Case Rates by Test Results and Treatment


```{r estimate_rates}

# Compile all participants' test results. Limit to successfully enrolled.
results <- subset(compile_results(to1clean),
                  StudyID %in% enrolled)


# Flag anyone who developed active TB
# Note: there's no guarantee this is the right variable for identifying
# those people, but I haven't seen any incident cases yet...
results$GotTB <- results$StudyID %in% 
    subset(to1clean$followupfortb, HasTb %in% 1)$StudyID


# Calculate approximate years of follow-up
results$years_fu <- as.numeric((Sys.Date() - results$EnrollDate)) / 365


# Melt it down to make aggregation easier
results.m <- melt(results,
                  id.vars = c("StudyID", "years_fu", "GotTB"),
                  measure.vars = c("tst", "qft", "tspot")
)

results.agg <- ddply(results.m,
                     .var = c("variable", "value"),
                     .fun = summarise,

    py_fu = sum(as.numeric(years_fu)),
    n_tb = sum(GotTB),
    rate = (n_tb / py_fu) * 1e5

)


# Set a prior for the estimates
prior_prop <- 300 / 1e5
prior_n <- 500
beta_param1 <- prior_prop * prior_n
beta_param2 <- (1 - prior_prop) * prior_n

# qplot(rbeta(prior_n, beta_param1, beta_param2), geom = "density")

rate_estimates <- ddply(results.agg, 
                        .var = c("variable", "value"), 
                        .fun = function(x) {

      estimate <- with(x, 
                       binom.bayes(x = n_tb, 
                                   n = py_fu,
                                   prior.shape1 = beta_param1,
                                   prior.shape2 = beta_param2,
                                   type = "highest")
      )

      data.frame(prop = estimate$mean,
                 py_fu = x$py_fu,
                 rate = estimate$mean * 1e5,
                 lower = estimate$lower * 1e5,
                 upper = estimate$upper * 1e5)

    }
)

cat("Total Participants Enrolled to Date: ",
    total_enrolled,
    "<br>")

cat("Total Incident Cases To Date: ", 
    sum(results$GotTB),
    "<br>")

cat("Total Person-Years of Follow-Up: ",
    sum(results$years_fu),
    "<br>")

cat("Rate per 100k Person-Years: ", 
    sum(results$GotTB) / sum(results$years_fu) * 1e5,
    "\n")

dfprint(rate_estimates)


```



## Which Test Is Most Strongly Associated with Triple-Positivity?





## Predicting Triple-Positive Results With Participant Characteristics


